#
# WARP
# Tools Ansible Role
# Tasks
#

- name: Install Development Tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "entr={{ devbox_entr_version }}"
    - "ripgrep={{ devbox_ripgrep_version }}"
    - "ranger={{ devbox_ranger_version }}"
    - "universal-ctags={{ devbox_universal_ctags_version }}"
    - "jq={{ devbox_jq_version }}"
    - "bind9-dnsutils={{ devbox_dnsutils_version }}"
    - "git-filter-repo={{ devbox_git_filter_repo_version }}"
    - "nnn={{ devbox_nnn_version }}"

- name: Install pre-commit with Pip
  become: true
  ansible.builtin.pip:
    name: "pre-commit=={{ devbox_pre_commit_version }}"
    state: present

- name: Install YQ YAML Processor
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ devbox_yq_version }}/yq_linux_amd64"
    dest: /usr/local/bin/yq
    mode: 0755

- name: Install Bitwarden CLI with NPM
  become: true
  community.general.npm:
    name: "@bitwarden/cli"
    global: true
    version: "{{ devbox_bw_version }} "
    state: present
