#
# WARP
# Tools Ansible Role
# Tasks
#

- name: Install Development Tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "entr={{ devbox_entr_version }}"
    - "ripgrep={{ devbox_ripgrep_version }}"
    - "ranger={{ devbox_ranger_version }}"
    - "universal-ctags={{ devbox_universal_ctags_version }}"
    - "jq={{ devbox_jq_version }}"
    - "git-filter-repo={{ devbox_git_filter_repo_version }}"
    - "htop={{ devbox_htop_version }}"
    - "fd-find={{ devbox_fd_version }}"
    - "bat={{ devbox_bat_version }}"
    - "chafa={{ devbox_chafa_version }}"
    - "proxychains4={{ devbox_proxychains_ng_version }}"
    - "mitmproxy={{ devbox_mitmproxy_version }}"
    - "direnv={{ devbox_direnv_version }}"
    - "sshfs={{ devbox_sshfs_version }}"

- name: Install Development Tools with Pip
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - "pre-commit=={{ devbox_pre_commit_version }}"
    - "codespell=={{ devbox_codespell_version }}"
    - "sqlfluff=={{ devbox_sqlfluff_version }}"
    - "shandy-sqlfmt=={{ devbox_sqlfmt_version }}"

- name: Install YQ YAML Processor
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ devbox_yq_version }}/yq_linux_amd64"
    dest: /usr/local/bin/yq
    mode: "0755"

- name: Install Development Tools with NPM
  become: true
  community.general.npm:
    name: "{{ item.name }}"
    global: true
    version: "{{ item.version }} "
    state: present
  loop:
    - name: "@bitwarden/cli"
      version: "{{ devbox_bw_version }}"
    - name: "tree-sitter-cli"
      version: "{{ devbox_tree_sitter_cli_version }}"
    - name: "prettier"
      version: "{{ devbox_prettier_version }}"

- name: Install Delta via ith APT
  become: true
  vars:
    version: "{{ devbox_delta_version }}"
  ansible.builtin.apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ version }}/git-delta_{{ version }}_amd64.deb"
