#
# WARP
# Box Ansible Playbook
# Console Tools
#

- name: Provision console tools
  hosts: all
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update APT Cache
      become: true
      ansible.builtin.apt:
        update-cache: true
  roles:
    - console
