#
# WARP
# Box Ansible Playbook
# GUI Enabled
#
#

- name: Provision Graphical tools
  hosts: all
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update APT Cache
      become: true
      ansible.builtin.apt:
        update-cache: true
  roles:
    - system
    - user
    - docker
    - pop_desktop
    - alacritty
    - flatpaks
    - gnome
    - globalprotect
    - remmina
    - anki
    - hotspot
    - borgbackup
    - virtualbox
    - power
