#
# WARP
# Box Ansible Playbook
# GUI Enabled
#
#

- name: Provision Graphical tools
  hosts: all
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update APT Cache
      become: true
      ansible.builtin.apt:
        update-cache: true
  roles:
    - console
    - pop_desktop
    - alacritty
    - flatpaks
    - dconfs
  post_tasks:
    - name: Optimize Storage Footprint & Performance
      ansible.builtin.import_tasks: tasks/optimize.yaml
