#
# WARP
# Box Ansible Playbook
# Laptop
#

- name: Provision Graphical tools
  hosts: all
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update APT Cache
      become: true
      ansible.builtin.apt:
        update-cache: true
  roles:
    - console
    - gui
    - borgbackup
    - tlp
    - btsuspend
  post_tasks:
    - name: Optimize Storage Footprint & Performance
      ansible.builtin.import_tasks: tasks/optimize.yaml
