#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  pre_tasks:
    - name: Check connectivity to Box
      ping: {}
  roles:
    - system
    - user
    - dotfiles

    - python
    - nodejs

    - openssh
    - rclone
    - neovim
    - docker
    - tools
    - devbox
    - ttyd
