#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  pre_tasks:
    - name: Check connectivity to Box
      ping: {}
  roles:
    - dotfiles
    - openssh
    - rclone
    - devbox
    - ttyd
