#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  vars:
    # User
    devbox_user: mrzzy
    devbox_user_home: /home/mrzzy

    # Optimizations
    # whether to optimize deployment for a small storage footprint
    devbox_minimize_storage: false
    # disable auto unattended upgrades
    devbox_uninstall_unattended_upgrades: true
  pre_tasks:
    - name: Update APT Cache
      become: true
      apt:
        update-cache: true
  roles:
    - system
    - user
    - dotfiles

    - openssh
    - ttyd

    - python
    - nodejs
    - jvm
    - c_cpp
    - go
    - js

    - zsh
    - tmux
    - neovim

    - fzf
    - rclone
    - tools

    - postgres

    - docker
    - cloud
    - k8s
    - shadowsocks
  post_tasks:
    - name: Optimize Storage Footprint & Performance
      import_tasks: tasks/optimize.yaml
