#
# WARP
# Box Ansible Playbook
#

- name: Provision console tools
  hosts: all
  vars:
    # User
    devbox_user: mrzzy
    devbox_user_home: /home/mrzzy
  pre_tasks:
    - name: Update APT Cache
      become: true
      apt:
        update-cache: true
  roles:
    - system
    - user
    - dotfiles

    - openssh
    - ttyd

    - python
    - nodejs
    - js
    - jvm
    - c_cpp
    - go
    - rust

    - zsh
    - tmux
    - neovim

    - fzf
    - rclone
    - tools

    - postgres

    - docker
    - cloud
    - k8s
    - shadowsocks

- name: Provision graphical tools
  hosts: all
  vars:
    # User
    devbox_user: mrzzy
    devbox_user_home: /home/mrzzy
  # only provision graphical tools when we can detect a X display
  roles:
    - role: flatpak
      tags: [test]
      when: "lookup('env', 'DISPLAY') != ''"
    - role: alacritty
      when: "lookup('env', 'DISPLAY') != ''"
    - role: spotify
      when: "lookup('env', 'DISPLAY') != ''"

  post_tasks:
    - name: Optimize Storage Footprint & Performance
      import_tasks: tasks/optimize.yaml
