#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  vars:
    # put ansible tmpdir in tmpfs when provisioning on remote machine
    # set permissions of tmpfile to world readable to avoid permission issues.
    ansible_remote_tmp: /tmp/ansible
    ansible_shell_allow_world_readable_temp: true
  pre_tasks:
    - name: Check connectivity to Box
      ping: {}
  roles:
    - devbox
    - ttyd
