#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  pre_tasks:
    - name: Check connectivity to Box
      ping: {}
  roles:
    - system
    - user
    - dotfiles

    - python
    - nodejs
    - jvm
    - c_cpp

    - openssh
    - zsh
    - tmux
    - neovim

    - fzf
    - rclone
    - tools

    - postgres

    - docker
    - cloud
    - k8s

    - devbox
    - ttyd
