#
# WARP
# Box Ansible Playbook
#

- name: Provision the WARP development Box
  hosts: all
  pre_tasks:
    - name: Check connectivity to Box
      ping: {}
    - name: Update APT Cache
      become: true
      apt:
        update-cache: true
  roles:
    - devbox
    - neovim
