#
# WARP
# System Playbook
# Tasks
#
- name: Provision System with Root Permissions
  hosts: all
  vars_files:
    - vars.yaml
  pre_tasks:
    - name: Update APT Cache
      become: true
      ansible.builtin.apt:
        update-cache: true
    - name: Get dpkg architecture
      command: dpkg --print-architecture
      register: dpkg_architecture
  roles:
    - system
    - user
