#
# WARP
# Box Ansible Playbook
# Variables
#

# configure ansible to use /tmp for temp files storage to avoid permission issues
ansible_remote_tmp: /tmp

# User settings
devbox_user: mrzzy
devbox_user_home: "/home/{{ devbox_user }}"

# Paths
devbox_asdf_install_path: "{{ devbox_user_home }}/.local/bin"
devbox_shell: "{{ devbox_asdf_install_path }}/zsh"
devbox_asdf_data_path: "{{ devbox_user_home }}/.asdf"
devbox_path: "{{ devbox_asdf_install_path }}:{{ devbox_asdf_data_path }}/shims:{{ ansible_env.PATH }}"
