#
# WARP
# Box Ansible Playbook
# Variables
#

# User settings
devbox_user: mrzzy
devbox_user_home: /home/mrzzy/

# Grpahical Applications
# Whether to provision graphical apps
devbox_install_graphical: false

# Optimizations
# whether to optimize deployment for a small storage footprint
devbox_minimize_storage: false
# disable auto unattended upgrades
devbox_uninstall_unattended_upgrades: true
