#
# WARP
# OpenSSH Ansible Role
# Tasks
#

- name: Install OpenSSH server with APT
  become: true
  ansible.builtin.apt:
    name: "openssh-server={{ devbox_openssh_server_version }}"
    state: present
