#
# WARP
# Rust role
# Default Variables
#

# renovate: datasource=github-releases depName=rust-lang/rust
devbox_rust_version: 1.76.0

# renovate: datasource=cargo depName=obsidian-export
devbox_obsidian_export_version: 22.11.0
