#
# WARP
# Naiveproxy Ansible Role
# Tasks
#
#

- name: Install 'naive' client binary
  become: true
  vars:
    version: "{{ devbox_naiveproxy_version }}"
    package_name: "naiveproxy-{{ devbox_naiveproxy_version }}-{{ ansible_system | lower }}-\
      {{ ansible_architecture | replace('86_', '') }}"
  block:
    - name: Download 'naive' client binary
      ansible.builtin.unarchive:
        remote_src: true
        src:
          "https://github.com/klzgrad/naiveproxy/releases/download/{{ version }}/{{ package_name }}.tar.xz"
        dest: /tmp
        creates: "/tmp/{{ package_name }}"

    - name: Copy 'naive' client binary to PATH
      ansible.builtin.copy:
        remote_src: true
        src: "/tmp/{{ package_name }}/naive"
        dest: /usr/local/bin/
        mode: "0755"
