#
# WARP
# GitHub Ansible Role
# Tasks
#

- name: Setup GitHub's Package Repository
  vars:
    key_path: /etc/apt/keyrings/github.gpg
  block:
    - name: "Register GitHub's package signing key"
      become: true
      ansible.builtin.get_url:
        url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
        dest: "{{ key_path }}"
        mode: "0644"
        client_cert:

    - name: Add GitHub's APT package repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ key_path }}] https://cli.github.com/packages stable main"
        state: present

- name: Install GitHub CLI with Apt
  become: true
  ansible.builtin.apt:
    name: "gh={{ devbox_github_cli_version }}"
    state: present
