#
# WARP
# ? Ansible Role
# Default Variables
#

# renovate: datasource=github-releases depName=kubernetes/kubernetes
devbox_kubectl_version: v1.25.3
# renovate: datasource=github-releases depName=helm/helm stripV
devbox_helm_version: 3.10.1
