#
# WARP
# Pre Commit hooks
#

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: ["-f", "lf"]

# check for secrets
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.8.6
  hooks:
    - id: gitleaks-docker

# check for spelling mistakes
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

# lint ansible playbooks
- repo: https://github.com/ansible-community/ansible-lint.git
  rev: v5.4.0
  hooks:
  - id: ansible-lint
    args: [
      "--project-dir", "box/ansible/",
      "--exclude", ".github/",
      "--exclude", ".pre-commit-config.yaml",
      "--exclude", "venv/"
    ]

# lint github actions workflows
- repo: https://github.com/sirosen/check-jsonschema.git
  rev: 0.13.0
  hooks:
  - id: check-github-workflows
