#
# WARP
# Development Environment
# Docker Compose
#

services:
  warp:
    image: ghcr.io/mrzzy/warp
    build: box
    ports:
      - 2222:22
      - 7681:7681
    # allow access to host docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOME}/Documents:/home/ubuntu/Documents"
