#
# WARP
# Development Environment
# Docker Compose
#

services:
  warp:
    image: ghcr.io/mrzzy/warp
    build: box
    # allow access to services running within the container
    network_mode: host
    # allow access to host docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${HOME}/Documents:/home/ubuntu/Documents"
