#
# WARP
# project makefile
#

# program vars
CD:=cd
VAGRANT:=vagrant
PACKER:=packer
PRE_CMT:=pre-commit
RM:=rm -rf

# paths
BOX_DIR:=box
BUILD_DIR:=build
PACKER_DIR:=$(BOX_DIR)/packer
ANSIBLE_DIR=$(BOX_DIR)/ansible

# phony build rules
.PHONY: all box clean fmt lint
.DEFAULT: all

all: box

lint:
	$(PACKER) init $(PACKER_DIR)
	$(PACKER) fmt -check $(PACKER_DIR)
	$(PACKER) validate $(PACKER_DIR)
	$(PRE_CMT) run

fmt:
	$(PACKER) fmt $(PACKER_DIR)

clean: clean-box

# build rules: WARP dev box VM
box: box/build/package.box

box/build/package.box: $(PACKER_DIR)
	$(PACKER) init $<
	$(PACKER) build --force $<

clean-box:
	$(RM) $(BUILD_DIR)

# use the Vagrantfile generated by packer to bring the box VM up
# the name of the machine is 'output', set by the Vagrantfile
run-box: $(BUILD_DIR)
	$(CD) $(BUILD_DIR) && $(VAGRANT) up
	$(CD) $(BUILD_DIR) && $(VAGRANT) ssh output
	$(CD) $(BUILD_DIR) && $(VAGRANT) halt
