#
# WARP
# Flatpak Ansible Role
# Tasks
#

# flatpak its itself installed by pop_desktop role
- name: Add the flathub flatpak repository remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak Apps from flathub
  become: true
  community.general.flatpak:
    remote: flathub
    name:
      # Spotify - music
      - com.spotify.Client
      # Zotero - reference management
      - org.zotero.Zotero
      # Obsidian - knowledge management
      - md.obsidian.Obsidian
      # Ticktick - todolist
      - com.ticktick.TickTick
      # Calibre - E books
      - com.calibre_ebook.calibre
      # Postman - REST API tester
      - flathub com.getpostman.Postman
    state: present
