#
# WARP
# Flatpak Ansible Role
# Tasks
#

# flatpak its itself installed by pop_desktop role
- name: Add the flathub flatpak repository remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak Apps from flathub
  become: true
  community.general.flatpak:
    remote: flathub
    name:
      - com.spotify.Client
      - org.zotero.Zotero
      - md.obsidian.Obsidian
      - com.ticktick.TickTick
    state: present
