#
# WARP
# Tectonic Ansible Role
# Tasks
#

- name: Install libfuse App Image dependency
  become: true
  ansible.builtin.apt:
    name: "libfuse2={{ devbox_libfuse_version }}"
    state: present

- name: Install Tectonic App Image
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/tectonic-typesetting/tectonic/releases/download/\
          tectonic%40{{ devbox_tectonic_version }}/tectonic-{{ devbox_tectonic_version }}-x86_64.AppImage"
    dest: "{{ devbox_tectonic_binary }}"
    mode: '0755'
