#
# WARP
# Devbox Ansible Role Tasks
# Install Programming Languages & Supporting Tooling
#

- name: Register NodeJS Repo
  include_tasks: register_nodejs.yaml

- name: Install NodeJS with APT
  become: true
  apt:
    # since the version of nodejs offered by registered repo is already pegged
    # there is no need to peg the version of nodejs installed here.
    name: "nodejs"
    state: present

- name: Install Python &amp; Tooling with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # python & tools
    - "python3={{ devbox_python_version }}"
    - "python3-pip={{ devbox_python_pip_version }}"
    - "python3-venv={{ devbox_python_venv_version }}"
    - "python-wheel-common={{ devbox_python_wheel_version }}"
