#
# WARP
# Devbox Ansible Role Tasks
# Install Programming Languages & Supporting Tooling
#

# JVM Languages
- name: Install JVM Languages & Tooling with SDKMan
  become: true
  import_role:
    role: comcast.sdkman
  vars:
    sdkman_dir: /usr/local/lib/sdkman
    sdkman_user: root
    sdkman_group: root
    sdkman_auto_answer: true
    sdkman_install_packages:
      - candidate: java
        version: "{{ devbox_jvm_java_version }}"
      - candidate: scala
        version: "{{ devbox_jvm_scala_version }}"
      - candidate: sbt
        version: "{{ devbox_jvm_sbt_version }}"

# C/C++
- name: Install C/C++ Tooling with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "cmake={{ devbox_c_cmake_version }}"
    - "clangd-12={{ devbox_c_clangd_version }}"
