#
# WARP
# Devbox Ansible Role Tasks
# Install Programming Languages & Supporting Tooling
#

# NodeJS
- name: Register NodeJS Repo
  import_tasks: register_nodejs.yaml
- name: Install NodeJS with APT
  become: true
  apt:
    # since the version of nodejs offered by registered repo is already pegged
    # there is no need to peg the version of nodejs installed here.
    name: "nodejs"
    state: present

# Python
- name: Install Python & Tooling with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # python & tools
    - "python3={{ devbox_python_version }}"
    - "python3-pip={{ devbox_python_pip_version }}"
    - "python3-venv={{ devbox_python_venv_version }}"
    - "python-wheel-common={{ devbox_python_wheel_version }}"

# JVM Languages
- name: Install JVM Languages & Tooling with SDKMan
  become: true
  import_role:
    role: comcast.sdkman
  vars:
    sdkman_dir: /usr/local/lib/sdkman
    sdkman_user: root
    sdkman_group: root
    sdkman_auto_answer: true
    sdkman_install_packages:
      - candidate: java
        version: "{{ devbox_jvm_java_version }}"
      - candidate: scala
        version: "{{ devbox_jvm_scala_version }}"
      - candidate: sbt
        version: "{{ devbox_jvm_sbt_version }}"
