#
# WARP
# GNOME settings Ansible Role
# Tasks
#

- name: Enable Hibernate in Shutdown Menu for Hibernate Status button
  become: true
  ansible.builtin.copy:
    content: |
      [Re-enable hibernate by default in upower]
      Identity=unix-user:*
      Action=org.freedesktop.upower.hibernate
      ResultActive=yes

      [Re-enable hibernate by default in logind]
      Identity=unix-user:*
      Action=org.freedesktop.login1.hibernate;org.freedesktop.login1.handle-hibernate-key;org.freedesktop.login1;org.freedesktop.login1.hibernate-multiple-sessions;org.freedesktop.login1.hibernate-ignore-inhibit
      ResultActive=yes
    dest: /etc/polkit-1/localauthority/50-local.d/com.ubuntu.hibernate.pkla
    mode: "0744"

- name: Configure GNOME desktop environment
  become: true
  ansible.builtin.import_role:
    name: ansible-role-customize-gnome
  vars:
    gnome_user: "{{ devbox_user }}"
    gnome_dconf:
      # map caps lock to escape key
      - key: /org/gnome/desktop/input-sources/xkb-options
        value: "['caps:escape']"
        # disable desktop animations
      - key: /org/gnome/desktop/interface/enable-animations
        value: "false"
        # show battery percentage on top bar
      - key: /org/gnome/desktop/interface/show-battery-percentage
        value: "true"
        # disable applications button on top bar
      - key: /org/gnome/shell/extensions/pop-cosmic/show-applications-button
        value: false
        # create media key shortcuts
      - key: /org/gnome/settings-daemon/plugins/media-keys/previous
        value: "['<Ctrl><Alt>j']"
      - key: /org/gnome/settings-daemon/plugins/media-keys/play
        value: "['<Ctrl><Alt>k']"
      - key: /org/gnome/settings-daemon/plugins/media-keys/next
        value: "['<Ctrl><Alt>l']"
        # custom shortcuts
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
        value: "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
        # map favourites key to TickTick
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name
        value: "'TickTick'"
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command
        value: "'flatpak run com.ticktick.TickTick'"
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding
        value: "'Favourites'"
        # power controls
      - key: /org/gnome/settings-daemon/plugins/power/power-button-action
        value: "'interactive'"
    gnome_extensions:
      # Hibernate Status Button
      - id: 755
        enable: true
      # Another Window Session Manager
      - id: 4709
        enable: true
    # JetBrains Mono font
    gnome_packages:
      - fonts-jetbrains-mono
    gnome_gsettings:
      - schema: org.gnome.desktop.interface
        key: monospace-font-name
        value: "'JetBrains Mono 16'"
