#
# WARP
# MySQL Ansible Role
# Tasks
#

- name: Install MySQL CLI with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "mysql-client={{ devbox_mysql_client_version }}"
    - "mycli={{ devbox_mycli_version }}"
