#
# WARP
# User Ansible Role
# Tasks
#

- name: Create groups
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - docker
    - ssl-cert

- name: Create devbox user
  become: true
  ansible.builtin.user:
    name: "{{ devbox_user }}"
    shell: "{{ devbox_shell }}"
    groups:
      # sudo group for passwordless sudo
      - sudo
      # docker group for sudo-free access to the docker CLI
      - docker
      # access to TLS certificates
      - ssl-cert

- name: Allow password-less sudo to users in sudo group
  become: true
  ansible.builtin.copy:
    content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/sudo_nopasswd
    mode: "0440"

- name: Allow ssl-cert group members to access TLS private keys
  become: true
  ansible.builtin.file:
    path: /etc/ssl/private/
    group: ssl-cert
    mode: "0710"
