#
# WARP
# Dotfiles Ansible Role
# Default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: b0a65999a43582a8ec90461ea154e13d3e0b6647
