#
# WARP
# Dotfiles Ansible Role
# Default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: ee1af4e52ee3f7a78b81c4d7b3dcf18760e5a6d5
