#
# WARP
# Dotfiles Ansible Role
# Default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: 2e73e73a00a7f34d5c905627705ff0d6c93d99d6
