#
# WARP
# System Ansible Role
# Tasks
#

- name: Install System utilities with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    # needed for add-apt-repository
    - "software-properties-common={{ devbox_software_properties_version }}"
    # needed for ansible to become a unprivilleged user
    - "acl={{ devbox_acl_version }}"
    # needed for ansible's git module
    - "git={{ devbox_git_version }}"
    # needed to authenticate packages from third-party repositories
    - "gpg={{ devbox_gpg_version }}"
    # openssl source code is common compile dependency
    - "libssl-dev={{ devbox_openssl_version }}"
    # needed to run app images
    - "libfuse2={{ devbox_libfuse_version }}"

- name: Register alacritty's terminfo with known Terminal Types
  become: true
  vars:
    terminfo_path: /tmp/alacritty.info
  block:
    - name: Download alacritty's terminfo
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
        dest: "{{ terminfo_path }}"
        mode: "0644"
    - name: Register alacritty's terminfo with database
      become: true
      ansible.builtin.command:
        cmd: "tic -x {{ terminfo_path }}"
        creates: /etc/terminfo/a/alacritty

- name: Modify kernel parameters with sysctl
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    val: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
  loop:
    # avoid using swap unless absolutely necessary
    - name: vm.swappiness
      value: 1
    # increase max number of programs & files a user can launch that watch for changes to
    - name: fs.inotify.max_user_instances
      value: 256
    - name: fs.inotify.max_user_watches
      value: 13170

# pin settings installed by pop os breaks ansible apt module's package resolution
- name: Remove Pop OS APT pin settings (if present)
  become: true
  ansible.builtin.file:
    name: /etc/apt/preferences.d/pop-default-settings
    state: absent
