#
# WARP
# AWS Ansible Role
# Tasks
#

- name: Setup AWS CLI
  vars:
    awscli_dist: /tmp/aws
  block:
    - name: Download AWS CLI
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_userspace_architecture }}.zip"
        dest: "{{ awscli_dist | dirname }}"
        creates: "{{ awscli_dist }}"

    - name: Install AWS CLI
      become: true
      ansible.builtin.command:
        cmd: >-
          {{ awscli_dist }}/install
            --install-dir {{ devbox_aws_cli_path }}
            --bin-dir {{ devbox_aws_cli_bin | dirname }}
        creates: "{{ devbox_aws_cli_path }}"
