#
# WARP
# FZF Ansible Role
# Tasks
#

- name: Download FZF install script
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/fzf/{{ devbox_fzf_version }}/install"
    dest: /tmp/install_fzf.sh
    mode: 0755

- name: Download FZF completion ZSH script
  become: true
  block:
    - name: Create FZF directory in /usr/local/share
      file:
        path: "{{ devbox_fzf_dir }}"
        state: directory
        mode: 0755

    - name: Download FZF key-bindings script for ZSH
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/fzf/{{ devbox_fzf_version }}/shell/key-bindings.zsh"
        dest: "{{ devbox_fzf_dir }}/key-bindings.zsh"
        mode: 0755

- name: Download FZF using install script
  command:
    cmd: bash /tmp/install_fzf.sh --bin --xdg
    creates: /tmp/bin/fzf

- name: Copy FZF Executable into Bin
  become: true
  copy:
    src: /tmp/bin/fzf
    remote_src: true
    mode: 0755
    dest: /usr/local/bin/fzf
