#
# WARP
# Alacritty Ansible Role
# Tasks
#

- name: Install Alacritty with APT
  become: true
  ansible.builtin.apt:
    name: "alacritty={{ devbox_alacritty_version }}"
    state: present

- name: Register Alacritty as the default X Terminal emulator
  become: true
  community.general.alternatives:
    name: x-terminal-emulator
    link: /usr/bin/x-terminal-emulator
    path: /usr/bin/alacritty
    state: selected

- name: Install Alacritty themes switcher with NPM
  become: true
  community.general.npm:
    name: "alacritty-themes@{{ devbox_alacritty_themes_version }}"
    global: true
    state: present

- name: Install JetBrains Mono Font for Alacritty
  vars:
    jetbrains_dir: /usr/share/fonts/truetype/jetbrains
  block:
    - name: Create directory for JetBrains Mono Font
      become: true
      ansible.builtin.file:
        dest: "{{ jetbrains_dir }}"
        state: directory
        mode: "0755"

    - name: Install JetBrains Mono Font
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: https://download.jetbrains.com/fonts/JetBrainsMono-2.304.zip
        dest: "{{ jetbrains_dir }}"
        creates: "{{ jetbrains_dir }}/fonts"

    - name: Rebuild Fonts cache # noqa no-changed-when
      ansible.builtin.command: fc-cache -v -f
