#
# WARP
# DuckDB Ansible Role
# Tasks
#

- name: Install 'duckdb' client binary
  become: true
  vars:
    package_name: "duckdb_cli-{{ ansible_system | lower }}-{{ ansible_architecture | replace('x86_', 'amd') }}"
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://github.com/duckdb/duckdb/releases/download/{{ devbox_duckdb_version }}/{{ package_name }}.zip"
    dest: /usr/local/bin
    creates: "/usr/local/bin/duckdb"
