#
# WARP
# Remmina Remote Desktop Viewer
# Tasks
#

- name: Install Remmina with APT
  tags: test
  become: true
  ansible.builtin.apt:
    name: "remmina={{ devbox_remmina_version }}"
    state: present
