#
# WARP
# Postgres Ansible Role
# Default Variables
#

# renovate: datasource=repology depName=ubuntu_22_04/pgcli
devbox_pgcli_version: 3.3.1-1
# renovate: datasource=repology depName=ubuntu_22_04/postgresql
devbox_postgresql_version: 14.7-0ubuntu0.22.04.1
