#
# WARP
# Golang Ansible Role
# Tasks
#

- name: Download Golang from go.dev
  become: true
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://go.dev/dl/go{{ devbox_golang_version }}.{{ ansible_system | lower }}-{{ ansible_architecture | replace('x86_', 'amd') }}.tar.gz"
    dest: "{{ devbox_golang_install_path | dirname }}"
    creates: "{{ devbox_golang_install_path }}"

- name: Make Golang binaries executable
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ devbox_golang_install_path }}/bin"
    mode: a+rx
    recurse: true
