#
# WARP
# Devtools Ansible Role Tasks
#

- name: Install Devtools with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "entr={{ devtools_entr_version }}"
    - "ripgrep={{ devtools_ripgrep_version }}"
    - "docker.io={{ devtools_docker_version }}"
    - "ranger={{ devtools_ranger_version }}"

- name: Install FZF
  import_tasks: install_fzf.yaml
  vars:
    fzf_version: "{{ devtools_fzf_version }}"

- name: "Download HashiCorp's package signing key"
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp_key

- name: "Register HashiCorp's package signing key"
  become: true
  command: apt-key add /tmp/hashicorp_key
  register: hashicorp_key
  changed_when: "hashicorp_key.rc == 0"

- name: "Add HashiCorp's APT package repository"
  become: true
  command: >-
    apt-add-repository
    --update
    "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  register: hashicorp_repo
  changed_when: "hashicorp_repo.rc == 0"

- name: Install Devtools from HashiCorp's Repository with APT"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "terraform={{ devtools_hashicorp_terraform_version }}"
    - "packer={{ devtools_hashicorp_packer_version }}"
