#
# WARP
# Shadowsocks Ansible Role
# Tasks
#

- name: Install shadowsocks-rust binaries
  become: true
  vars:
    version: "{{ devbox_shadowsocks_version }}"
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://github.com/shadowsocks/shadowsocks-rust/releases/download/{{ version }}\
          /shadowsocks-{{ version }}.{{ ansible_architecture }}-unknown-linux-gnu.tar.xz"
    dest: /usr/local/bin
    creates: /usr/local/bin/sslocal
