#
# WARP
# Postgres Ansible Role
# Tasks
#

- name: Install Postgres Tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "pgcli={{ devbox_pgcli_version }}"
    - "postgresql-client-14={{ devbox_postgresql_version }}"
