#
# WARP
# Devbox Ansible Role
# Default Variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy
# Optimizations
# whether to optimize deployment for a small storage footprint
devbox_minimize_storage: false
# disable auto unattended upgrades
devbox_uninstall_unattended_upgrades: true
