#
# WARP
# Devbox Ansible Role default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: 8e4c2ac9ee4f34602837659dde625b817245fa56

# system tools
# needed for add-apt-repository
# renovate: datasource=repology depName=ubuntu_20_04/software-properties
devbox_software_properties_version: 0.99.9.8
# load iptables rules on boot
# renovate: datasource=repology depName=ubuntu_20_04/iptables-persistent
devbox_iptables_persistent_version: 1.0.14ubuntu1
# needed for ansible to become a unprivilleged user
# renovate: datasource=repology depName=ubuntu_20_04/acl
devbox_acl_version: 2.2.53-6

# Neovim text editor
# renovate: datasource=repology depName=ubuntu_20_04/neovim
devbox_nvim_version: 0.4.3-3
# renovate: datasource=github-releases depName=junegunn/vim-plug
devbox_nvim_vim_plug_version: 0.11.0
# renovate: datasource=pypi depName=pynvim versioning=python
devbox_nvim_pynvim_version: 0.4.3

# Language-agnostic tools
# renovate: datasource=repology depName=ubuntu_20_04/entr
devbox_entr_version: 4.4-1
# renovate: datasource=repology depName=ubuntu_20_04/rust-ripgrep
devbox_ripgrep_version: 11.0.2-1ubuntu0.1
# renovate: datasource=repology depName=ubuntu_20_04/docker.io
devbox_docker_version: 20.10.12-0ubuntu2~20.04.1
# renovate: datasource=github-releases depName=docker/compose
devbox_docker_compose_version: v2.11.1
# renovate: datasource=repology depName=ubuntu_20_04/ranger
devbox_ranger_version: 1.9.3-1build1
# renovate: datasource=repology depName=ubuntu_20_04/ansible
devbox_ansible_version: 5.10.0-1ppa~focal
# renovate: datasource=repology depName=ubuntu_20_04/gawk
devbox_gawk_version: 1:5.0.1+dfsg-1
# renovate: datasource=repology depName=ubuntu_20_04/universal-ctags
devbox_universal_ctags_version: 0+git20181215-2
# renovate: datasource=repology depName=ubuntu_20_04/jq
devbox_jq_version: 1.6-1ubuntu0.20.04.1
# renovate: datasource=repology depName=ubuntu_20_04/bind9-dnsutils
devbox_dnsutils_version: 1:9.16.1-0ubuntu2.11

# renovate: datasource=pypi depName=pre-commit
devbox_pre_commit_version: 2.20.0
# renovate: datasource=github-releases depName=rclone/rclone
devbox_rclone_version: v1.59.2
# renovate: datasource=npm depName=@bitwarden/cli versioning=npm
# TODO(mrzzy): is this useful? maybe remove.
devbox_bw_version: 2022.8.0

# renovate: datasource=repology depName=ubuntu_20_04/zsh
devbox_zsh_version: 5.8-3ubuntu1.1
# renovate: datasource=repology depName=ubuntu_20_04/zsh-autosuggestions
devbox_zsh_autosuggest_version: 0.6.4-1
# renovate: datasource=repology depName=ubuntu_20_04/zsh-syntax-highlighting
devbox_zsh_syntax_version: 0.6.0-3

# renovate: datasource=repology depName=ubuntu_20_04/tmux
devbox_tmux_version: 3.0a-2ubuntu0.3

# renovate: datasource=github-releases depName=junegunn/fzf
devbox_fzf_version: 0.33.0
devbox_fzf_dir: /usr/local/share/fzf

# python & tools
# renovate: datasource=repology depName=ubuntu_20_04/python3.8
devbox_python_version: 3.8.10-0ubuntu1~20.04.5
# renovate: datasource=repology depName=ubuntu_20_04/python-pip
devbox_python_pip_version: 20.0.2-5ubuntu1.6
# renovate: datasource=repology depName=ubuntu_20_04/wheel
devbox_python_wheel_version: 0.34.2-1

# jvm languages & tools
devbox_jvm_java_version: 11.0.15-tem
# TODO(mrzzy): remove scala as it can installed by sbt
devbox_jvm_scala_version: 3.1.3
# renovate: datasource=maven depName=org.scala-sbt:sbt versioning=maven
devbox_jvm_sbt_version: 1.7.1

# c/c++ tools
# renovate: datasource=repology depName=ubuntu_20_04/cmake
devbox_c_cmake_version: 3.16.3-1ubuntu1
devbox_c_clangd_version: "1:12.0.0-3ubuntu1~20.04.5"

# yaml tools
# renovate: datasource=github-releases depName=mikefarah/yq
devbox_yq_version: v4.27.5

# postgresql tools
# renovate: datasource=repology depName=ubuntu_20_04/pgcli
devbox_pgcli_version: 2.2.0-4

# cloud tools
# renovate: datasource=github-releases depName=hashicorp/terraform versioning=hashicorp stripV
devbox_hashicorp_terraform_version: 1.2.2
# renovate: datasource=github-releases depName=hashicorp/terraform-ls versioning=hashicorp stripV
devbox_hashicorp_terraform_langserver_version: 0.29.1
# renovate: datasource=github-releases depName=hashicorp/packer versioning=hashicorp stripV
devbox_hashicorp_packer_version: 1.8.0
# renovate: datasource=pypi depName=linode-cli versioning=python
devbox_linode_cli_version: 5.23.0

# kubernetes tools
# renovate: datasource=github-releases depName=kubernetes/kubernetes
devbox_kubectl_version: v1.25.1
# renovate: datasource=github-releases depName=helm/helm stripV
devbox_helm_version: 3.9.4

# Optimizations
# whether to optimize deployment for a small storage footprint
devbox_minimize_storage: true
# disable auto unattended upgrades
devbox_uninstall_unattended_upgrades: true
