#
# WARP
# Devbox Ansible Role default variables
#

devbox_user: mrzzy
devbox_user_home: /home/mrzzy

# git revision of dotfiles to install
devbox_dotfiles_rev: fc1e01cf9675ec769a7238394d190f1cb238b088

# whether to optimize deployment for a small storage footprint
devbox_minimize_storage: false

# system tools
# needed for add-apt-repository
devbox_software_properties_version: 0.99.9.8
# load iptables rules on boot
devbox_iptables_persistent_version: 1.0.14ubuntu1
# needed for ansible to become a unprivilleged user
devbox_acl_version: 2.2.53-6

# Neovim text editor
devbox_nvim_version: 0.4.3-3
devbox_nvim_vim_plug_version: 0.11.0
devbox_nvim_pynvim_version: 0.4.3

# Language-agnostic tools
devbox_entr_version: 4.4-1
devbox_ripgrep_version: 11.0.2-1build1
devbox_docker_version: 20.10.12-0ubuntu2~20.04.1
devbox_docker_compose_version: v2.6.1
devbox_ranger_version: 1.9.3-1build1
devbox_ansible_version: 5.10.0-1ppa~focal
devbox_gawk_version: 1:5.0.1+dfsg-1
devbox_universal_ctags_version: 0+git20181215-2
devbox_jq_version: 1.6-1ubuntu0.20.04.1

devbox_pre_commit_version: 2.20.0
devbox_rclone_version: v1.59.1
devbox_bw_version: 2022.8.0

devbox_zsh_version: 5.8-3ubuntu1.1
devbox_zsh_autosuggest_version: 0.6.4-1
devbox_zsh_syntax_version: 0.6.0-3

devbox_tmux_version: 3.0a-2ubuntu0.3

devbox_hashicorp_terraform_version: 1.2.2
devbox_hashicorp_terraform_langserver_version: 0.29.2
devbox_hashicorp_packer_version: 1.8.0

devbox_fzf_version: 0.29.0
devbox_fzf_dir: /usr/local/share/fzf

# python & tools
devbox_python_version: 3.8.2-0ubuntu2
devbox_python_pip_version: 20.0.2-5ubuntu1.6
devbox_python_venv_version: 3.8.2-0ubuntu2
devbox_python_wheel_version: 0.34.2-1

# jvm languages & tools
devbox_jvm_java_version: 11.0.15-tem
devbox_jvm_scala_version: 3.1.3
devbox_jvm_sbt_version: 1.7.1

# c/c++ tools
devbox_c_cmake_version: 3.16.3-1ubuntu1
devbox_c_clangd_version: "1:12.0.0-3ubuntu1~20.04.5"

# yaml tools
devbox_yq_version: v4.27.2

# postgresql tools
devbox_pgcli_version: 2.2.0-4

# kubernetes tools
devbox_kubectl_version: v1.24.0
devbox_helm_version: 3.9.1-1
devbox_kubectl_gke_auth_plugin_version: 398.0.0-0
