#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal
#

- name: Download pre-built TTYD Binary
  ansible.builtin.get_url:
    url: "https://github.com/tsl0922/ttyd/releases/download/{{ devbox_ttyd_version }}/ttyd.{{ ansible_architecture }}"
    dest: "{{ devbox_ttyd_path }}"
    mode: "0755"
