#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal
#

- name: Download pre-built TTYD Binary
  become: true
  get_url:
    url: "https://github.com/tsl0922/ttyd/releases/download/{{ devbox_ttyd_version }}/ttyd.x86_64"
    dest: "{{ devbox_ttyd_path }}"
    mode: 0755

- name: Write TTYD over HTTPS systemd service
  copy:
    content: |
      [Unit]
      Description=TTYD enables shell access a web terminal over HTTPS
      ConditionPathExists={{ devbox_ttyd_tls_cert }}
      ConditionPathExists={{ devbox_ttyd_tls_private_key }}

      [Install]
      WantedBy=multi-user.target

      [Service]
      Type=simple
      WorkingDirectory={{ devbox_user_home }}
      # start ttyd on a unprivilleged port as the unprivilleged devbox user
      ExecStart=sudo --user {{ devbox_user }} --group {{ devbox_user }} --login -n \
        {{ devbox_ttyd_path }} \
          --port {{ devbox_ttyd_https_port }} \
          --credential "{{ devbox_user }}:{{ devbox_ttyd_password }}" \
          --ssl \
          --ssl-cert {{ devbox_ttyd_tls_cert }} \
          --ssl-key {{ devbox_ttyd_tls_private_key }} \
          /usr/bin/zsh
    dest: /etc/systemd/system/ttyd-https.service
    mode: 0644

- name: Write TTYD over HTTP systemd service
  copy:
    content: |
      [Unit]
      Description=TTYD enables shell access a web terminal over HTTP

      [Install]
      WantedBy=multi-user.target
      After=ttyd-https.service

      [Service]
      Type=simple
      WorkingDirectory={{ devbox_user_home }}
      # start ttyd on a unprivilleged port as the unprivilleged devbox user
      ExecStart=sudo --user {{ devbox_user }} --group {{ devbox_user }} --login -n \
        {{ devbox_ttyd_path }} \
          --port {{ devbox_ttyd_http_port }} \
          /usr/bin/zsh
    dest: /etc/systemd/system/ttyd-http.service
    mode: 0644

- name: Enable TTYD
  # disable ttyd if password is unset to avoid exposing an unauthenticated web shell
  when: devbox_ttyd_password != ""
  block:
    - name: Activate TTYD systemd services
      systemd:
        name: "{{ item }}"
        enabled: true
      loop:
        - ttyd-https
        - ttyd-http

    - name: Write IPV4 TTYD iptables rules to be loaded by iptables-persistent
      become: true
      vars:
        interface: "{{ ansible_default_ipv4.interface }}"
      copy:
        content: |
          *nat
          # forward incoming traffic via the default ipv4 interface to TTYD
          -A PREROUTING -i {{ interface }} -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{ devbox_ttyd_http_port }}
          -A PREROUTING -i {{ interface }} -p tcp -m tcp --dport 443 -j REDIRECT --to-ports {{ devbox_ttyd_https_port }}
          COMMIT
        dest: /etc/iptables/rules.v4
        mode: 0644
