#
# WARP
# Rclone Ansible Role
# Tasks
#

- name: Install rclone via .deb package with APT
  become: true
  vars:
    version: "{{ devbox_rclone_version }}"
  apt:
    deb: "https://downloads.rclone.org/{{ version }}/rclone-{{ version }}-linux-amd64.deb"

- name: Install rclone as mount helper (mount -t) for rclone FS type
  become: true
  file:
    src: /usr/bin/rclone
    dest: /sbin/mount.rclone
    state: link
    mode: '0755'
