#
# WARP
# Rclone Ansible Role
# Tasks
#

- name: Install rclone via .deb package with APT
  become: true
  vars:
    version: "{{ devbox_rclone_version }}"
  ansible.builtin.apt:
    deb: "https://downloads.rclone.org/{{ version }}/rclone-{{ version }}-linux-amd64.deb"

- name: Install rclone as mount helper (mount -t) for rclone FS type
  become: true
  ansible.builtin.file:
    src: /usr/bin/rclone
    dest: /sbin/mount.rclone
    state: link
    mode: '0755'

- name: Create rclone config directory in /etc
  become: true
  ansible.builtin.file:
    state: directory
    path: "/etc/rclone"
    mode: "0700"
