#
# WARP
# Azure Ansible Role
# Tasks
#


- name: Setup Azure APT package repository
  vars:
    tmp_path: /tmp/microsoft.asc
    key_path: /etc/apt/keyrings/microsoft.gpg
  become: true
  block:
    - name: Register Azure APT Package Signing Key
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: "{{ tmp_path }}"
        mode: "0644"
    - name: Dearmor Azure APT Package Signing Key
      ansible.builtin.command:
        cmd: "gpg -o {{ key_path }} --dearmor {{ tmp_path }}"
        creates: "{{ key_path }}"
    - name: Add Azure APT Package Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_path }}] \
               https://packages.microsoft.com/repos/azure-cli {{ ansible_lsb['codename'] }} main"
        filename: azure-cli
        state: present

- name: Install Azure CLI with APT
  become: true
  ansible.builtin.apt:
    name: "azure-cli={{ devbox_azure_cli_version }}"
    state: present
