#
# WARP
# ZSH Ansible Role
# Tasks
#
- name: Install ZSH with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "zsh={{ devbox_zsh_version }}"
    - "zsh-autosuggestions={{ devbox_zsh_autosuggest_version }} "
    - "zsh-syntax-highlighting={{ devbox_zsh_syntax_version }}"

- name: Install Z Jump Tool
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/agkozak/zsh-z/master/zsh-z.plugin.zsh
    dest: "/usr/local/share/zsh/site-functions"
    mode: "0644"

- name: Install Atuin shell history tool
  become: true
  ansible.builtin.apt:
    deb: https://github.com/ellie/atuin/releases/download/v{{ devbox_atuin_version }}/atuin_{{ devbox_atuin_version }}_amd64.deb
