#
# WARP
# ASDF role
# Tasks
#

- name: Install ASDF via Git
  become: true
  become_user: "{{ devbox_user }}"
  ansible.builtin.git:
    repo: "https://github.com/asdf-vm/asdf"
    single_branch: true
    version: "{{ devbox_asdf_version }}"
    dest: "{{ devbox_asdf_path }}"

- name: Install ASDF Plugins
  become: true
  become_user: "{{ devbox_user }}"
  ansible.builtin.command:
    cmd: "asdf plugin add {{ item.name }} {{ item.value }}"
    creates: "{{ devbox_asdf_path }}/{{ item.name }}"
  loop:
    - name: nodejs
      repo: https://github.com/asdf-vm/asdf-nodejs.git
    - name: python
      repo: https://github.com/danhper/asdf-python.git
    - name: cmake
      repo: https://github.com/asdf-community/asdf-cmake.git
    - name: golang
      repo: https://github.com/asdf-community/asdf-golang.github
    - name: infracost
      repo: https://github.com/dex4er/asdf-infracost.git

    # jvm
    - name: java
      repo: https://github.com/halcyon/asdf-java.git
    - name: maven
      repo: https://github.com/halcyon/asdf-maven
    - name: gradle
      repo: https://github.com/rfrancis/asdf-gradle.git
    - name: sbt
      repo: https://github.com/bram2000/asdf-sbt.git

    # hashicorp
    - name: terraform
      repo: https://github.com/asdf-community/asdf-hashicorp.git
    - name: terraform-ls
      repo: https://github.com/asdf-community/asdf-hashicorp.git
    - name: packer
      repo: https://github.com/asdf-community/asdf-hashicorp.git

    # kubernetes
    - name: kubectl
      repo: https://github.com/asdf-community/asdf-kubectl.git
    - name: helm
      repo: https://github.com/Antiarchitect/asdf-helm.git
    - name: kind
      repo: https://github.com/johnlayton/asdf-kind.git
