#
# WARP
# Devbox Ansible Role Tasks
# Kubernetes Tools
#

- name: Install Kubernetes pre-built binary tools
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: 0755
  loop:
    - name: kubectl
      url: "https://dl.k8s.io/release/{{ devbox_kubectl_version }}/bin/linux/amd64/kubectl"
    - name: kind
      url: "https://kind.sigs.k8s.io/dl/{{ devbox_kind_version }}/kind-linux-amd64"

- name: Install GKE Auth Plugin for Kubectl
  vars:
    key_path: /etc/apt/keyrings/cloud.google.gpg
  become: true
  block:
    - name: Add GCP APT Package Signing Key
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: "{{ key_path }}"
        mode: 0644
    - name: Add GCP APT Package Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_path }}] \
               https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present
    - name: Install GKE Auth Plugin
      ansible.builtin.apt:
        name: "google-cloud-sdk-gke-gcloud-auth-plugin"
        state: present

- name: Install Helm form Third-Party Balto repository
  vars:
    key_path: /etc/apt/keyrings/baltocdn.asc
  block:
    - name: "Download Balto's package signing key"
      become: true
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: "{{ key_path }}"
        mode: 0644

    - name: "Add Balto's APT package repository"
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_path }}] https://baltocdn.com/helm/stable/debian/ all main"
        state: present

    - name: "Install Helm from Balto's APT package repository"
      become: true
      ansible.builtin.apt:
        name: "helm={{ devbox_helm_version }}-1"
        state: present
