#
# WARP
# Devbox Ansible Role Tasks
# Kubernetes Tools
#

- name: Install Kubernetes pre-built binary tools
  become: true
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: "0755"
  loop:
    - name: kubectl
      url: "https://dl.k8s.io/release/{{ devbox_kubectl_version }}/bin/linux/amd64/kubectl"
    - name: kind
      url: "https://kind.sigs.k8s.io/dl/{{ devbox_kind_version }}/kind-linux-amd64"

- name: Install Helm binary
  block:
    - name: Download Helm binary
      ansible.builtin.unarchive:
        remote_src: true
        src: https://get.helm.sh/helm-{{ devbox_helm_version }}-linux-amd64.tar.gz
        dest: /tmp
        include: [linux-amd64/helm]
    - name: Move Helm binary into PATH
      become: true
      vars:
        helm_src: /tmp/linux-amd64/helm
        helm_dest: /usr/local/bin/helm
      ansible.builtin.command:
        cmd: "mv {{ helm_src }}  {{ helm_dest }}"
        removes: "{{ helm_src }}"
        creates: "{{ helm_dest }}"
