#
# WARP
# PopOS Desktop Ansible Role
# Role Tasks
#

- name: Setup PopOS APT Repository
  vars:
    key_path: /etc/apt/keyrings/popos.gpg
  block:
    - name: Add PopOS APT Repository signing Key
      become: true
      ansible.builtin.command:
        cmd: "gpg --no-default-keyring \
          --keyring {{ key_path }} \
          --keyserver keyserver.ubuntu.com \
          --recv-keys 63C46DF0140D738961429F4E204DD8AEC33A7AFF"
        creates: "{{ key_path }}"

    - name: Register PopOS APT Repository
      become: true
      ansible.builtin.copy:
        content: |
          X-Repolib-Name: Pop_OS Release Sources
          Enabled: yes
          Types: deb deb-src
          URIs: https://apt.pop-os.org/release
          Suites: jammy
          Components: main
          Signed-By: {{ key_path }}
        dest: /etc/apt/sources.list.d/pop-os-release.sources
        mode: 0644

- name: Install pop-desktop with APT
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: pop-desktop
    state: present

# restore apt lists for future apt commands
- name: Update APT Cache
  become: true
  ansible.builtin.apt:
    update_cache: true
