#
# WARP
# PopOS Desktop Ansible Role
# Role Tasks
#

- name: Add PopOS APT Repository signing Key
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 63C46DF0140D738961429F4E204DD8AEC33A7AFF

- name: Register PopOS APT Repository
  become: true
  ansible.builtin.copy:
    content: |
      X-Repolib-Name: Pop_OS Release Sources
      Enabled: yes
      Types: deb deb-src
      URIs: https://apt.pop-os.org/release
      Suites: jammy
      Components: main
    dest: /etc/apt/sources.list.d/pop-os-release.sources
    mode: 0644

- name: Update APT Cache to pull PopOS package lists
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install pop-desktop with APT
  become: true
  ansible.builtin.apt:
    name: pop-desktop
    state: present
