#
# WARP
# Devbox Ansible Role Tasks
# Install Helm from Third Party Repo
#

- name: "Download Balto's package signing key"
  get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /tmp/baltocdn_key

- name: "Register Balto's package signing key"
  become: true
  command: apt-key add /tmp/baltocdn_key
  register: hashicorp_key
  changed_when: "hashicorp_key.rc == 0"

- name: "Add Balto's APT package repository"
  become: true
  apt_repository:
    repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
    state: present

- name: "Install Helm from Balto's APT package repository"
  become: true
  apt:
    name: "helm={{ devbox_helm_version }}-1"
    state: present
