#
# WARP
# Devbox Ansible Role Tasks
# Install development tooling
#

- name: Register Ansible APT PPA
  become: true
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present

- name: Install development tools with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # language-agnostic tools
    - "entr={{ devbox_entr_version }}"
    - "ripgrep={{ devbox_ripgrep_version }}"
    - "docker.io={{ devbox_docker_version }}"
    - "ranger={{ devbox_ranger_version }}"
    - "ansible={{ devbox_ansible_version }}"
    - "neovim={{ devbox_nvim_version }}"
    - "zsh={{ devbox_zsh_version }}"
    - "zsh-autosuggestions={{ devbox_zsh_autosuggest_version }} "
    - "zsh-syntax-highlighting={{ devbox_zsh_syntax_version }}"
    - "tmux={{ devbox_tmux_version }}"
    - "gawk={{ devbox_gawk_version }}"
    - "universal-ctags={{ devbox_universal_ctags_version }}"
    - "jq={{ devbox_jq_version }}"

    # postgresql tools
    - "pgcli={{ devbox_pgcli_version }}"

- name: Install Development Tools with Pip
  become: true
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - "pre-commit=={{ devbox_pre_commit_version }}"
    # neovim client for python
    - "pynvim=={{ devbox_nvim_pynvim_version }}"

- name: Install Bitwarden CLI with NPM
  become: true
  npm:
    name: "@bitwarden/cli"
    global: true
    version: "{{ devbox_bw_version }} "
    state: present

- name: Install FZF
  vars:
    fzf_version: "{{ devbox_fzf_version }}"
  import_tasks: install_fzf.yaml

- name: Install Z Jump Tool
  become: true
  vars:
    zsh_scripts_dir: "{{ devbox_user_home }}/.local/share/zsh"
  import_tasks: install_z_jump.yaml

- name: Install tools from HashiCorp's Repository with APT"
  import_tasks: install_hashicorp.yaml

- name: Install docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/\
          {{ devbox_docker_compose_version }}/docker-compose-linux-\
          {{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

# Kubernetes Tools
- name: Install Kubectl
  become: true
  get_url:
    url: "https://dl.k8s.io/release/{{ devbox_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: 0755
- name: Install GKE Auth Plugin for Kubectl
  become: true
  block:
    - name: Add GCP APT Package Signing Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/cloud.google.gpg
        state: present
    - name: Add GCP APT Package Repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
               https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present
    - name: Install GKE Auth Plugin
      apt:
        name: "google-cloud-sdk-gke-gcloud-auth-plugin={{ devbox_kubectl_gke_auth_plugin_version }}"
        state: present

- name: Install Helm
  import_tasks: install_helm.yaml
