#
# WARP
# Devbox Ansible Role Tasks
# Install Kubectl
#

- name: "Download & Install Kubectl"
  become: true
  get_url:
    url: "https://dl.k8s.io/release/{{ devbox_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: 0755
