#
# WARP
# Devbox Ansible Role Tasks
# Install development tooling
#

- name: Register Ansible APT PPA
  become: true
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present

- name: Register NodeJS Repo
  include_tasks: register_nodejs.yaml

- name: Update APT Cache
  become: true
  apt:
    update-cache: true

- name: Install development tools with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "entr={{ devbox_entr_version }}"
    - "ripgrep={{ devbox_ripgrep_version }}"
    - "docker.io={{ devbox_docker_version }}"
    - "docker-compose={{ devbox_docker_compose_version }}"
    - "ranger={{ devbox_ranger_version }}"
    - "ansible={{ devbox_ansible_version }}"
    - "neovim={{ devbox_nvim_version }}"
    - "zsh={{ devbox_zsh_version }}"
    - "zsh-autosuggestions={{ devbox_zsh_autosuggest_version }} "
    - "zsh-syntax-highlighting={{ devbox_zsh_syntax_version }}"
    - "tmux={{ devbox_tmux_version }}"
    - "gawk={{ devbox_gawk_version }}"
    - "universal-ctags={{ devbox_universal_ctags_version }}"

    # since the version of nodejs offered by registered repo is already pegged
    # there is no need to peg the version of nodejs installed here.
    - "nodejs"

    # python & tools
    - "python3={{ devbox_python_version }}"
    - "python3-pip={{ devbox_python_pip_version }}"
    - "python3-venv={{ devbox_python_venv_version }}"

    # postgresql tools
    - "pgcli={{ devbox_pgcli_version }}"

- name: Install FZF
  vars:
    fzf_version: "{{ devbox_fzf_version }}"
  import_tasks: install_fzf.yaml

- name: Install Z Jump Tool
  become: true
  vars:
    zsh_scripts_dir: "{{ devbox_user_home }}/.local/share/zsh"
  import_tasks: install_z_jump.yaml

- name: Install TTYD Web Terminal
  become: true
  vars:
    ttyd_path: /usr/local/bin/ttyd
  import_tasks: install_ttyd.yaml

- name: Install tools from HashiCorp's Repository with APT"
  import_tasks: install_hashicorp.yaml
  vars:
    terraform_version: "{{ devbox_hashicorp_terraform_version }}"
    packer_version: "{{ devbox_hashicorp_packer_version }}"
