#
# WARP
# Devbox Ansible Role Tasks
# Install ttyd Web Terminal
#

- name: Download pre-built TTYD Binary
  get_url:
    url: "https://github.com/tsl0922/ttyd/releases/download/{{ devbox_ttyd_version }}/ttyd.x86_64"
    dest: /usr/local/bin/ttyd
    mode: 0755
