#
# WARP
# Devbox Ansible Role Tasks
# Install ttyd Web Terminal
#

- name: Download pre-built TTYD Binary
  get_url:
    url: "https://github.com/tsl0922/ttyd/releases/download/{{ devbox_ttyd_version }}/ttyd.x86_64"
    dest: "{{ ttyd_path }}"
    mode: 0755

- name: Activate systemd service to start TTYD on boot
  block:
    - name: Write systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web termina

          [Install]
          WantedBy=multi-user.target

          [Service]
          Type=simple
          ExecStart={{ ttyd_path }} --port 7681 /usr/bin/zsh
          User=mrzzy
          Group=mrzzy
          WorkingDirectory=/home/mrzzy
        dest: /etc/systemd/system/ttyd.service
        mode: 0644

    - name: Activate systemd service
      systemd:
        name: ttyd
        state: started
        enabled: true
