#
# WARP
# Devbox Ansible Role Tasks
# Kubernetes Tools
#

- name: Install Kubectl
  become: true
  get_url:
    url: "https://dl.k8s.io/release/{{ devbox_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: 0755

- name: Install GKE Auth Plugin for Kubectl
  become: true
  block:
    - name: Add GCP APT Package Signing Key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /usr/share/keyrings/cloud.google.gpg
        state: present
    - name: Add GCP APT Package Repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
               https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present
    - name: Install GKE Auth Plugin
      apt:
        name: "google-cloud-sdk-gke-gcloud-auth-plugin"
        state: present

- name: Install Helm
  import_tasks: install_helm.yaml
