#
# WARP
# Devbox Ansible Role Tasks
# Install development tooling
#

- name: Register Ansible APT PPA
  become: true
  apt_repository:
    repo: "ppa:ansible/ansible"
    state: present

- name: Install development tools with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # language-agnostic tools
    - "entr={{ devbox_entr_version }}"
    - "ripgrep={{ devbox_ripgrep_version }}"
    - "docker.io={{ devbox_docker_version }}"
    - "ranger={{ devbox_ranger_version }}"
    - "ansible={{ devbox_ansible_version }}"
    - "neovim={{ devbox_nvim_version }}"
    - "zsh={{ devbox_zsh_version }}"
    - "zsh-autosuggestions={{ devbox_zsh_autosuggest_version }} "
    - "zsh-syntax-highlighting={{ devbox_zsh_syntax_version }}"
    - "tmux={{ devbox_tmux_version }}"
    - "gawk={{ devbox_gawk_version }}"
    - "universal-ctags={{ devbox_universal_ctags_version }}"
    - "jq={{ devbox_jq_version }}"
    - "bind9-dnsutils={{ devbox_dnsutils_version }}"

    # postgresql tools
    - "pgcli={{ devbox_pgcli_version }}"

- name: Install Development Tools with Pip
  become: true
  pip:
    name: "{{ item }}"
    state: present
  loop:
    - "pre-commit=={{ devbox_pre_commit_version }}"
    - "linode-cli=={{ devbox_linode_cli_version }}"

- name: Install Bitwarden CLI with NPM
  become: true
  npm:
    name: "@bitwarden/cli"
    global: true
    version: "{{ devbox_bw_version }} "
    state: present

- name: Install FZF
  vars:
    fzf_version: "{{ devbox_fzf_version }}"
  import_tasks: install_fzf.yaml

- name: Install Z Jump Tool
  become: true
  get_url:
    url: https://raw.githubusercontent.com/agkozak/zsh-z/master/zsh-z.plugin.zsh
    dest: "/usr/local/share/zsh/site-functions"

- name: Install tools from HashiCorp's Repository with APT"
  import_tasks: install_hashicorp.yaml

- name: Install docker-compose
  become: true
  get_url:
    url: "https://github.com/docker/compose/releases/download/\
          {{ devbox_docker_compose_version }}/docker-compose-linux-\
          {{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Install Kubernetes Tools
  import_tasks: install_k8s.yaml

- name: Install infracost
  vars:
    infracost_binary: /usr/local/bin/infracost-linux-amd64
  become: true
  import_tasks: install_infracost.yaml
