#
# WARP
# Miniconda Ansible Role
# Default Variables
#


# renovate: datasource=github-releases depName=conda/conda
devbox_conda_version: 23.11.0
# miniconda installation prefix
devbox_conda_prefix: /home/mrzzy/.conda
