#
# WARP
# Neovim Ansible Role
# Install NodeJS
#

- name: Download NodeJS 16.x Install Script
  become: true
  get_url:
    url: https://deb.nodesource.com/setup_16.x
    dest: /tmp/register_nodejs_repo.sh
    mode: 744

- name: Register NodeJS Package Repository
  become: true
  command: /tmp/register_nodejs_repo.sh
  register: register_nodejs
  changed_when: '"Run `sudo apt-get install -y nodejs`" in register_nodejs'

- name: Install NodeJS
  become: true
  apt:
    # TODO(mrzzy): figure out a way to peg the node js version
    name: "nodejs={{ nodejs_version }}"
    state: present
