#
# WARP
# Neovim Ansible Role Tasks
#

# Setup neovim
- name: Install Neovim
  become: true
  apt:
    name: neovim={{ nvim.version }}
    state: present

- name: Create Neovim directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0774
  loop:
    - ~/.config/nvim/
    - ~/.local/share/nvim/site/autoload/

- name: Pull Neovim config init.vim
  get_url:
    url: https://raw.githubusercontent.com/mrzzy/dotfiles/main/.config/nvim/init.vim
    dest: ~/.config/nvim/init.vim

# Editor Tooling
- name: Register NodeJS Repo
  include_tasks: register_nodejs.yaml

- name: Install Snap Editor Tooling
  become: true
  snap:
    name: universal-ctags
  loop: "{{ nvim.tooling.snap | dict2items }}"

- name: Install Apt Editor Tooling
  become: true
  apt:
    name: '{{ item.key }}{{ "={}".format(item.value) if item.value else "" }}'
    state: present
  loop: "{{ nvim.tooling.apt | dict2items }}"

- name: Install FZF
  include_tasks: install_fzf.yaml
  vars:
    fzf_version: "{{ nvim.plugins.fzf }}"

# Plugins
- name: Install vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/{{ nvim.plugins.vim_plug }}/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install Neovim Plugins
  command:
    cmd: nvim +PlugInstall +qall
    creates: ~/.local/share/nvim/plugged
