#
# WARP
# Neovim Ansible Role
# Tasks
#

- name: Install Neovim Plugins
  environment:
    XDG_CONFIG_HOME: "{{ devbox_user_home }}/.config"
    XDG_DATA_HOME: "{{ devbox_user_home }}/.local/share"
    XDG_STATE_HOME: "{{ devbox_user_home }}/.local/state"
    PATH: "{{ devbox_path }}"
  block:
    - name: Install lazy.nvim plugin manager
      ansible.builtin.git:
        repo: https://github.com/folke/lazy.nvim
        version: "{{ devbox_nvim_lazy_version }}"
        single_branch: true
        dest: "{{ devbox_user_home }}/.local/share/nvim/site/pack/lazy/start/lazy"
        # silence 'will clobber existing tag' error for 'stable' tag that is constantly updated
        force: true

      # needed for neovim linter
    - name: Install codespell
      ansible.builtin.pip:
        name: codespell
        version: "{{ devbox_codespell_version }}"
        # python >=3.11 necessary for pip install
        extra_args: --user --break-system-packages

    - name: Install Neovim Plugins
      ansible.builtin.command:
        cmd: nvim --headless "+Lazy! sync" +qa
        creates: "{{ devbox_user_home }}.local/share/nvim/lazy"
