#
# WARP
# Neovim Ansible Role Tasks
#

# Setup neovim
- name: Install Neovim
  become: true
  apt:
    name: neovim={{ nvim_version }}
    state: present

- name: Create Neovim directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0774
  loop:
    - ~/.config/nvim/
    - ~/.local/share/nvim/site/autoload/

- name: Pull Neovim config init.vim
  get_url:
    url: https://raw.githubusercontent.com/mrzzy/dotfiles/main/.config/nvim/init.vim
    dest: ~/.config/nvim/init.vim

# Editor Tooling
- name: Register NodeJS Repo
  include_tasks: register_nodejs.yaml

- name: Install NodeJS
  become: true
  apt:
    name: nodejs
    state: present

- name: Install Snap Editor Tooling
  become: true
  snap:
    name: universal-ctags

# Plugins
- name: Install vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/{{ nvim_vim_plug_version }}/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install Neovim Plugins
  command:
    cmd: nvim +PlugInstall +qall
    creates: ~/.local/share/nvim/plugged
