#
# WARP
# Neovim Ansible Role Tasks
#

- name: Install Neovim
  become: true
  apt:
    name: neovim={{ nvim_version }}
    state: present

- name: Create Neovim directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/nvim/
    - ~/.local/share/nvim/site/autoload/

- name: Pull Neovim config init.vim
  get_url:
    url: https://raw.githubusercontent.com/mrzzy/dotfiles/main/.config/nvim/init.vim
    dest: ~/.config/nvim/init.vim

- name: Install vim-plugin plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/{{ nvim_vim_plug_version }}/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
