#
# WARP
# Neovim Ansible Role
# Tasks
#

- name: Install Neovim with APT
  become: true
  apt:
    name: "neovim={{ devbox_nvim_version }}"
    state: present

- name: Install Neovim Plugins
  become: true
  become_user: "{{ devbox_user }}"
  block:
    - name: Install packer.nvim plugin manager
      git:
        repo: https://github.com/wbthomason/packer.nvim
        version: "{{ devbox_nvim_packer_version }}"
        dest: "{{ devbox_user_home }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

    - name: Run packer.nvim PackInstall to install plugin
      # direct plugins to be installed in devbox users's home dir
      environment:
        HOME: "{{ devbox_user_home }}"
        XDG_CONFIG_HOME: "{{ devbox_user_home }}/.config"
        XDG_DATA_HOME: "{{ devbox_user_home }}/.local/share"
        XDG_STATE_HOME: "{{ devbox_user_home }}/.local/state"
      command:
        cmd: nvim --headless +PackInstall +qall
        creates: "{{ devbox_user_home }}/.local/share/nvim/plugged"

    - name: Install coc.nvim extensions
      command:
        cmd: nvim --headless '+call Install_coc_extensions()' +qall
        creates: "{[ devbox_user_home }}/.config/coc/extensions"
