#
# WARP
# Neovim Ansible Role
# Tasks
#

- name: Install Neovim App image
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ devbox_nvim_version }}/nvim.appimage"
    dest: /usr/local/bin/nvim
    mode: "0755"

- name: Install Neovim Plugins
  become: true
  become_user: "{{ devbox_user }}"
  environment:
    HOME: "{{ devbox_user_home }}"
    XDG_CONFIG_HOME: "{{ devbox_user_home }}/.config"
    XDG_DATA_HOME: "{{ devbox_user_home }}/.local/share"
    XDG_STATE_HOME: "{{ devbox_user_home }}/.local/state"
  ansible.builtin.command:
    cmd: nvim --headless "+Lazy! sync" +qa
    creates: "{{ devbox_user_home }}.local/share/nvim/lazy"
