#
# WARP
# Neovim Ansible Role Tasks
#

# Setup neovim
- name: Install Neovim
  become: true
  apt:
    name: neovim={{ nvim.version }}
    state: present

- name: Create Neovim directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0664
  loop:
    - ~/.config/nvim/
    - ~/.local/share/nvim/site/autoload/

- name: Pull Neovim config init.vim
  get_url:
    url: https://raw.githubusercontent.com/mrzzy/dotfiles/main/.config/nvim/init.vim
    dest: ~/.config/nvim/init.vim

# Editor Tooling
- name: Install NodeJS
  include_tasks: install_nodejs.yaml
  vars:
    nodejs_version: "{{nvim.plugins.nodejs}}"

- name: Install Snap Editor Tooling
  become: true
  snap:
    name: universal-ctags
  loop: "{{ nvim.tooling.snap | dict2items }}"

- name: Install Apt Editor Tooling
  become: true
  apt:
    name: "{{ item.key }}={{ item.value }}"
    state: present
  loop: "{{ nvim.tooling.apt | dict2items }}"

# Plugins
- name: Install vim-plug plugin manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/{{ nvim.plugins.vim_plug }}/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install Neovim Plugins
  command: nvim +PlugInstall +qall
  args:
    creates: ~/.local/share/nvim/plugged
