#
# WARP
# Neovim Ansible Role
# Register NodeJS Repo
#

- name: Download NodeJS 16.x Install Script
  become: true
  get_url:
    url: https://deb.nodesource.com/setup_16.x
    dest: /tmp/register_nodejs_repo.sh
    mode: 744

- name: Register NodeJS Package Repository
  become: true
  command: /tmp/register_nodejs_repo.sh
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
