#
# WARP
# Intel Vtune Role
# Tasks
#

- name: Setup Intel package repository
  vars:
    tmp_path: /tmp/intel.asc
    key_path: /etc/apt/keyrings/intel.gpg
  become: true
  block:
    - name: Register Intel APT Package Signing Key
      ansible.builtin.get_url:
        url: https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        dest: "{{ tmp_path }}"
        mode: "0644"
    - name: Dearmor Intel APT Package Signing Key
      ansible.builtin.command:
        cmd: "gpg -o {{ key_path }} --dearmor {{ tmp_path }}"
        creates: "{{ key_path }}"
    - name: Add Intel APT Package Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_path }}] \
          https://apt.repos.intel.com/oneapi all main"
        filename: intel
        state: present

- name: Install with Apt
  become: true
  ansible.builtin.apt:
    name: "gh={{ devbox_github_cli_version }}"
    state: present
