#
# WARP
# Tmux Ansible Role
# Tasks
#

- name: Install Tmux & AWK with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "tmux={{ devbox_tmux_version }}"
    - "gawk={{ devbox_tmux_gawk_version }}"

- name: Install Tmux Plugins
  become: true
  become_user: "{{ devbox_user }}"
  vars:
    tpm_path: "{{ devbox_tmux_tpm_path }}"
  block:
    - name: Install Tmux Plugin Manager (TPM)
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ tpm_path }}"
        version: master
        single_branch: true

    - name: Run TPM install_plugins
      environment:
        # needed to point TPM to install plugins in the devbox users home dir not root
        HOME: "{{ devbox_user_home }}"
      ansible.builtin.command:
        cmd: "{{ tpm_path }}/bin/install_plugins"
        creates: "{{ tpm_path }}/plugins"

- name: Install Tmux Systemd service
  tags: [test]
  become: true
  become_user: "{{ devbox_user }}"
  vars:
    systemd_dir: "{{ devbox_user_home }}/.config/systemd/user"
  block:
    - name: Create user Systemd Units directory
      ansible.builtin.file:
        dest: "{{ systemd_dir }}"
        state: directory
        mode: "0750"
    - name: Template Tmux Systemd service
      ansible.builtin.template:
        src: templates/tmux.service.j2
        dest: "{{ systemd_dir }}/tmux.service"
        mode: "0744"

- name: Start & Enable Tmux Systemd Service
  tags: [test]
  become: true
  become_user: "{{ devbox_user }}"
  ansible.builtin.systemd:
    scope: user
    name: tmux
    state: started
    enabled: true
    daemon_reload: true
