#
# WARP
# ASDF Version Manager Role
# Default Variables
#

# renovate: datasource=github-releases depName=asdf-vm/asdf
devbox_asdf_version: v0.18.0

devbox_asdf_plugins:
  - name: jq
    versions: [1.7.1]
  - name: ripgrep
    # renovate: datasource=github-releases depName=BurntSushi/ripgrep
    versions: [14.1.1]
  - name: fd
    # renovate: datasource=github-releases depName=sharkdp/fd stripV
    versions: [10.2.0]
  - name: bat
    # renovate: datasource=github-releases depName=sharkdp/bat stripV
    versions: [0.25.0]
  - name: fzf
    # renovate: datasource=github-releases depName=sharkdp/bat stripV
    versions: [0.61.3]
  - name: direnv
    # renovate: datasource=github-releases depName=direnv/direnv stripV
    versions: [2.36.0]
  - name: github-cli
    # renovate: datasource=github-releases depName=cli/cli stripV
    versions: [2.72.0]
  - name: neovim
    versions: [0.11.1]
  - name: tmux
    # renovate: datasource=github-releases depName=tmux/tmux
    versions: [3.5a]
  # neovim plugin dependencies
  - name: nodejs
    versions: [22.15.0]
  - name: coursier
    versions: [2.1.24]
  - name: golang
    versions: [1.24.2]
  - name: rust
    versions: [1.86.0]
  # tmux plugin dependencies
  # tmux-cpu-mem-info
  - name: cmake
    versions: [4.0.3]
  - name: python
    versions:
      - 3.10.15
      - 3.11.13
