#
# WARP
# HashiCorp Ansible Role
# Tasks
#

# HashiCorp Tools
- name: Setup HashiCorp's APT package Repository
  vars:
    key_path: /etc/apt/keyrings/hashicorp.asc
  block:
    - name: "Register HashiCorp's package signing key"
      become: true
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "{{ key_path }}"
        mode: "0644"

    - name: Add HashiCorp's APT package repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ key_path }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

- name: Install HashiCorp tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "terraform={{ devbox_hashicorp_terraform_version }}-1"
    - "packer={{ devbox_hashicorp_packer_version }}-1"
    - "terraform-ls={{ devbox_hashicorp_terraform_langserver_version }}-1"
    - "vagrant={{ devbox_hashicorp_vagrant_version }}"
