#
# WARP
# TTYD Ansible Role default variables
#

# TTYD web terminal
# renovate: datasource=github-tags depName=tsl0922/ttyd
devbox_ttyd_version: 1.7.7
devbox_ttyd_path: "{{ devbox_user_home }}/.local/bin/ttyd"
