#
# WARP
# Cloud Ansible Role
# Tasks
#

- name: Install Cloud tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "virtualbox={{ devbox_virtualbox_version }}"

- name: Install Cloud tools with Pip
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - "ansible-base=={{ devbox_ansible_version }}"
    - "ansible-lint=={{ devbox_ansible_lint_version }}"

# Install Infracost
- name: Install Infracost
  become: true
  vars:
    infracost_binary: /usr/local/bin/infracost-linux-amd64
  block:
    - name: Download Infracost binary
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://github.com/infracost/infracost/releases/download/\
              {{ devbox_infracost_version }}/infracost-linux-amd64.tar.gz"
        dest: /usr/local/bin
        creates: "{{ infracost_binary }}"
        mode: 0755

    - name: Strip suffix from Infracost binary
      ansible.builtin.command:
        cmd: "mv {{ infracost_binary }} /usr/local/bin/infracost"
        removes: "{{ infracost_binary }}"
        creates: /usr/local/bin/infracost"
