#
# WARP
# Cloud Ansible Role
# Tasks
#

# HashiCorp Tools
- name: Setup HashiCorp's APT package Repository
  vars:
    key_path: /etc/apt/keyrings/hashicorp.gpg
  block:
    - name: "Register HashiCorp's package signing key"
      become: true
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "{{ key_path }}"
        mode: 0644

    - name: Add HashiCorp's APT package repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by={{ key_path }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

- name: Install Cloud tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - "terraform={{ devbox_hashicorp_terraform_version }}"
    - "packer={{ devbox_hashicorp_packer_version }}"
    - "terraform-ls={{ devbox_hashicorp_terraform_langserver_version }}"
    - "vagrant={{ devbox_hashicorp_vagrant_version }}"
    - "virtualbox={{ devbox_virtualbox_version }}"

- name: Install Cloud tools with Pip
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - "linode-cli=={{ devbox_linode_cli_version }}"
    - "ansible-base=={{ devbox_ansible_version }}"
    - "ansible-lint=={{ devbox_ansible_lint_version }}"

# Install Infracost
- name: Install Infracost
  become: true
  vars:
    infracost_binary: /usr/local/bin/infracost-linux-amd64
  block:
    - name: Download Infracost binary
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://github.com/infracost/infracost/releases/download/\
              {{ devbox_infracost_version }}/infracost-linux-amd64.tar.gz"
        dest: /usr/local/bin
        creates: "{{ infracost_binary }}"
        mode: 0755

    - name: Strip suffix from Infracost binary
      ansible.builtin.command:
        cmd: "mv {{ infracost_binary }} /usr/local/bin/infracost"
        removes: "{{ infracost_binary }}"
        creates: /usr/local/bin/infracost"
