#
# WARP
# Cloud Ansible Role
# Tasks
#

- name: Install Cloud tools with Pip
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - "ansible-base=={{ devbox_ansible_version }}"
    - "ansible-lint=={{ devbox_ansible_lint_version }}"
