#
# WARP
# JVM Ansible Role
# Tasks
#

- name: Install Java & Tooling with SDKMan
  become: true
  ansible.builtin.import_role:
    role: Comcast.sdkman
  vars:
    sdkman_dir: /usr/local/lib/sdkman
    sdkman_user: root
    sdkman_group: root
    sdkman_auto_answer: true
    sdkman_install_packages:
      - candidate: java
        version: "{{ devbox_java_version }}"
      - candidate: maven
        version: "{{ devbox_maven_version }}"
      - candidate: gradle
        version: "{{ devbox_gradle_version }}"

- name: Install Coursier
  vars:
    coursier: /usr/local/bin/cs
  block:
    - name: Download Coursier
      ansible.builtin.get_url:
        url: "https://github.com/coursier/coursier/releases/download/\
              {{ devbox_coursier_version }}/cs-x86_64-pc-linux.gz"
        dest: /tmp/coursier.gz
        mode: "0744"
    - name: Uncompress Coursier
      become: true
      ansible.builtin.shell:
        cmd: "gunzip -c /tmp/coursier.gz >{{ coursier }}"
        creates: "{{ coursier }}"
    - name: Make Coursier executable
      become: true
      ansible.builtin.file:
        path: "{{ coursier }}"
        mode: "0755"

- name: Install Scala & Tooling with Coursier
  become: true
  become_user: "{{ devbox_user }}"
  vars:
    coursier_bin: "{{ devbox_user_home }}/.local/share/coursier/bin"
  ansible.builtin.command:
    cmd: "cs install {{ item }}"
    creates: "{{ coursier_bin }}/bin"
  loop:
    - "scala:{{ devbox_scala_version }}"
    - "sbt:{{ devbox_sbt_version }}"
