#
# WARP
# OpenSSH Ansible Role
# Default Variables
#

# renovate: datasource=repology depName=ubuntu_20_04/openssh
devbox_openssh_server_version: 1:8.2p1-4ubuntu0.5
# niceness level of high priority processes (ie. ssh)
devbox_priority_nice_level: -2
