#
# WARP
# Devbox Ansible Role Tasks
# Install system utilities
#

- name: Download pre-built TTYD Binary
  become: true
  get_url:
    url: "https://github.com/tsl0922/ttyd/releases/download/{{ devbox_ttyd_version }}/ttyd.x86_64"
    dest: "{{ devbox_ttyd_path }}"
    mode: 0755

- name: Install system utilities with TTYD
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "software-properties-common={{ devbox_software_properties_version }}"
    - "iptables-persistent={{ devbox_iptables_persistent_version }}"
    - "acl={{ devbox_acl_version }}"
