#
# WARP
# Devbox Ansible Role Tasks
# Install system utilities
#

- name: Install system utilities with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "software-properties-common={{ devbox_software_properties_version }}"
    - "iptables-persistent={{ devbox_iptables_persistent_version }}"
    - "acl={{ devbox_acl_version }}"
    - "openssh-server={{ devbox_openssh_server_version }}"

- name: Install rclone via .deb package with APT
  become: true
  vars:
    version: "{{ devbox_rclone_version }}"
  apt:
    deb: "https://downloads.rclone.org/{{ version }}/rclone-{{ version }}-linux-amd64.deb"

- name: Install rclone as mount helper (mount -t) for rclone FS type
  become: true
  file:
    src: /usr/bin/rclone
    dest: /sbin/mount.rclone
    state: link
    mode: '0755'

- name: Increase process priority of SSH server
  become: true
  lineinfile:
    path: /etc/systemd/system/sshd.service
    regex: '^Nice='
    insertafter: '\[Service\]'
    line: 'Nice={{ devbox_priority_nice_level }}'

- name: Register alacritty's terminfo with known Terminal Types
  vars:
    terminfo_path: /tmp/alacritty.info
  block:
    - name: Download alacritty's terminfo
      get_url:
        url: https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info
        dest: "{{ terminfo_path }}"
    - name: Register alacritty's terminfo with database
      become: true
      command:
        cmd: "tic -x {{ terminfo_path }}"
        creates: /etc/terminfo/a/alacritty
