#
# WARP
# Devbox Ansible Role Tasks
#

# update apt lists for installing packages
- name: Update APT Cache
  become: true
  apt:
    update-cache: true

# Install
# install programming languages
- name: Install Programming Languages & Tooling
  import_tasks: languages/install.yaml

# install development tooling
- name: Install Development Tooling
  import_tasks: tooling/install.yaml

# Optimizations
- name: Optimize Storage Footprint & Performance
  import_tasks: optimize.yaml
