#
# WARP
# Devbox Ansible Role Tasks
#

# Install
# install ttyd web terminal
- name: Install TTYD Web Terminal
  become: true
  import_tasks: install_ttyd.yaml

# install development tooling
- name: Install Development Tooling
  import_tasks: tooling/install.yaml

# install customized dotfiles
- name: Install dotfiles
  become: true
  block:
    - name: Pull bare dotfiles repository
      git:
        repo: https://github.com/mrzzy/dotfiles
        version: main
        single_branch: true
        dest: "{{ devbox_user_home }}/.git"
        bare: true

    - name: Unmark repo as bare to allow checkouts
      community.general.git_config:
        name: core.bare
        scope: file
        file: "{{ devbox_user_home }}/.git/config"
        state: absent

    # workaround git security patch for CVE-2022-24765
    # https://github.blog/2022-04-12-git-security-vulnerability-announced/
    - name: Trust non-owned repository
      community.general.git_config:
        name: safe.directory
        value: "{{ devbox_user_home }}"

    - name: Checkout dotfiles
      command: # noqa command-instead-of-module
        cmd: git checkout
        chdir: "{{ devbox_user_home }}"
      register: checkout
      changed_when: checkout.rc == 0

# Setup
# setup ttyd web terminal
- name: Setup TTYD Web Terminal
  include_tasks: setup_ttyd.yaml
  # disable ttyd if password is unset to avoid exposing an unauthenticated web shell
  when: devbox_ttyd_password == ""
  tags:
    - test

# setup development tooling
- name: Setup Neovim
  become: true
  import_tasks: setup_nvim.yaml
- name: Setup Tmux
  become: true
  import_tasks: setup_tmux.yaml


# User Accounts
# create user & permissions
- name: Setup User Accounts & Permissions
  become: true
  block:
    - name: Create groups
      group:
        name: "{{ item }}"
        state: present
      loop:
        - sudo
        - docker

    - name: Create devbox user
      user:
        name: "{{ devbox_user }}"
        home: "{{ devbox_user_home }}"
        shell: /bin/zsh
        groups:
          # sudo group for passwordless sudo
          - sudo
          # docker group for sudo-free access to the docker CLI
          - docker

    - name: Allow password-less sudo to users in sudo group
      copy:
        content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/sudo_nopasswd
        mode: 0440

    - name: Fix owner of devbox home directory
      file:
        path: "{{ devbox_user_home }}"
        owner: "{{ devbox_user }}"
        group: "{{ devbox_user }}"
        state: directory
        recurse: true
