#
# WARP
# Devbox Ansible Role Tasks
#

- name: Install Development Tooling
  import_tasks: tooling/main.yaml

# setup accounts & permissions
- name: Create groups
  become: true
  group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - docker

- name: Create mrzzy User
  become: true
  user:
    name: mrzzy
    comment: "Zhu Zhanyan"
    uid: 1000
    groups:
      # sudo group for passwordless sudo
      - sudo
      # docker group for sudo-free access to the docker CLI
      - docker

# setup development tooling
- name: Setup Neovim
  import_tasks: setup_nvim.yaml
