#
# WARP
# Devbox Ansible Role Tasks
#

- name: Install Development Tooling
  import_tasks: tooling/install.yaml

- name: Setup User Accounts & Permissions
  become: true
  block:
  - name: Create groups
    group:
      name: "{{ item }}"
      state: present
    loop:
      - sudo
      - docker

  - name: Create mrzzy user
    user:
      name: mrzzy
      comment: "Zhu Zhanyan"
      uid: 1000
      groups:
        # sudo group for passwordless sudo
        - sudo
        # docker group for sudo-free access to the docker CLI
        - docker

  - name: Allow password-less sudo to users in sudo group
    copy:
      content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
      dest: /etc/sudoers.d/sudo_nopasswd
      mode: 0440

# setup development tooling
- name: Setup Neovim
  import_tasks: setup_nvim.yaml
