#
# WARP
# Devbox Ansible Role Tasks
#

# update apt lists for installing packages
- name: Update APT Cache
  become: true
  apt:
    update-cache: true

# Install
# install programming languages
- name: Install Programming Languages & Tooling
  import_tasks: languages/install.yaml

# install development tooling
- name: Install Development Tooling
  import_tasks: tooling/install.yaml

# Setup User
- name: Setup Devbox User
  become: true
  become_user: "{{ devbox_user }}"
  block:
    - name: Setup Neovim
      import_tasks: setup_nvim.yaml

    - name: Setup Tmux
      import_tasks: setup_tmux.yaml

# Optimizations
- name: Optimize Storage Footprint & Performance
  import_tasks: optimize.yaml
