#
# WARP
# Devbox Ansible Role Tasks
#

# update apt lists for installing packages
- name: Update APT Cache
  become: true
  apt:
    update-cache: true

# Install
# install system utilities
- name: Install System Utilities
  import_tasks: install_system.yaml

# install programming languages
- name: Install Programming Languages & Tooling
  import_tasks: languages/install.yaml

# install development tooling
- name: Install Development Tooling
  import_tasks: tooling/install.yaml

# User Accounts
# create user & permissions
- name: Setup User Accounts & Permissions
  import_tasks: setup_users.yaml

# Setup User
- name: Setup Development Tooling for Devbox User
  become: true
  become_user: "{{ devbox_user }}"
  block:
    - name: Download dotfiles
      block:
        - name: Git clone dotfiles
          git:
            repo: https://github.com/mrzzy/dotfiles
            dest: "{{ devbox_user_home }}"
            version: "{{ devbox_dotfiles_rev }}"

    - name: Setup Neovim
      import_tasks: setup_nvim.yaml

    - name: Setup Tmux
      import_tasks: setup_tmux.yaml

# Optimizations
- name: Optimize Storage Footprint & Performance
  import_tasks: optimize.yaml
