#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal
#

- name: Setup systemd services to run TTYD on boot
  become: true
  block:
    - name: Write TTYD over HTTPS systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web terminal over HTTPS
          ConditionPathExists={{ devbox_ttyd_tls_cert }}
          ConditionPathExists={{ devbox_ttyd_tls_private_key }}

          [Install]
          WantedBy=multi-user.target

          [Service]
          Type=simple
          WorkingDirectory={{ devbox_user_home }}
          # start ttyd on a unprivilleged port as the unprivilleged devbox user
          ExecStart=sudo --user {{ devbox_user }} --group {{ devbox_user }} --login -n \
            {{ devbox_ttyd_path }} \
              --port 7681 \
              --credential "{{ devbox_user }}:{{ devbox_ttyd_password }}" \
              --ssl \
              --ssl-cert {{ devbox_ttyd_tls_cert }} \
              --ssl-key {{ devbox_ttyd_tls_private_key }} \
              /usr/bin/zsh

          # use iptables to redirect HTTPs traffic to the web terminal
          ExecStartPost=iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 7681
          ExecStopPost=iptables -D PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 7681

        dest: /etc/systemd/system/ttyd-https.service
        mode: 0644

    - name: Write TTYD over HTTP systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web terminal over HTTP

          [Install]
          WantedBy=multi-user.target
          After=ttyd-https.service

          [Service]
          Type=simple
          WorkingDirectory={{ devbox_user_home }}
          # start ttyd on a unprivilleged port as the unprivilleged devbox user
          ExecStart=sudo --user {{ devbox_user }} --group {{ devbox_user }} --login -n \
            {{ devbox_ttyd_path }} \
              --port 7682 \
              /usr/bin/zsh

          # use iptables to redirect HTTP traffic to the web terminal
          ExecStartPost=iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 7682
          ExecStopPost=iptables -D PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 7682

        dest: /etc/systemd/system/ttyd-http.service
        mode: 0644

    - name: Activate TTYD systemd services
      systemd:
        name: "{{ item }}"
        enabled: true
      loop:
        - ttyd-https
        - ttyd-http
