#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal
#

- name: Setup systemd services to run TTYD on boot
  become: true
  block:
    - name: Write TTYD systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web terminal

          [Install]
          WantedBy=multi-user.target

          [Service]
          Type=simple
          WorkingDirectory={{ devbox_user_home }}
          # start ttyd on a unprivilleged port as the unprivilleged devbox user
          ExecStart=sudo --user {{ devbox_user }} --group {{ devbox_user }} --login -n \
            {{ devbox_ttyd_path }} \
              --port 7681 \
              --credential "{{ devbox_user }}:{{ devbox_ttyd_password }}" \
              --ssl \
              --ssl-cert /etc/letsencrypt/live/vm.warp.mrzzy.co/fullchain.pem \
              --ssl-key /etc/letsencrypt/live/vm.warp.mrzzy.co/privkey.pem \
              /usr/bin/zsh

          # use iptables to redirect HTTPs traffic to the web terminal
          ExecStartPost=iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 7681
          ExecStopPost=iptables -D PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 7681

        dest: /etc/systemd/system/ttyd.service
        mode: 0644

    - name: Activate TTYD systemd service
      systemd:
        name: ttyd
        enabled: true
