#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal & Certbot for TLS
#

- name: Setup systemd services to run Certbot & TTYD on boot
  become: true
  block:
    - name: Write Certbot systemd service
      copy:
        content: |
          [Unit]
          Description=Certbot procures a trusted TLS certificate from Lets Encrypt

          [Service]
          Type=oneshot
          ExecStart=/snap/bin/certbot certonly -n \
            --standalone \
            --key-type ecdsa \
            --agree-tos \
            --preferred-challenges http \
            --domains {{ devbox_tls_domain }} \
            --email {{ devbox_tls_letsencrypt_email }} \
            {% if devbox_tls_letsencrypt_staging %}--test-cert{% endif %}
          # since ttyd will run as the devbox user, admend permissions to ensure
          # certificate & private key are accessible.
          # -L needed as certificate as symlinked into the directory
          ExecStartPost=/usr/bin/chgrp -L {{ devbox_user }} /etc/

        dest: /etc/systemd/system/certbot.service
        mode: 0644

    - name: Write TTYD systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web terminal
          Wants=certbot.service
          After=certbot.service

          [Install]
          WantedBy=multi-user.target

          [Service]
          Type=simple
          User={{ devbox_user }}
          Group={{ devbox_user }}
          WorkingDirectory={{ devbox_user_home }}
          # start ttyd on a unprivilleged port as unprivilleged devbox user &
          # use iptables to redirect HTTPs traffic to the web terminal
          ExecStart={{ devbox_ttyd_path }} \
            --port 7681 \
            --credentials "{{ devbox_user }}:{{ devbox_ttyd_password }}" \
            # use the TLS certificates provisioned by certbot
            --ssl \
            --ssl-cert /etc/letsencrypt/live/vm.warp.mrzzy.co/fullchain.pem \
            --ssl-key /etc/letsencrypt/live/vm.warp.mrzzy.co/privkey.pem \
            /usr/bin/zsh
          ExecStartPost=iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 7681
          ExecStopPost=iptables -D PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 7681

        dest: /etc/systemd/system/ttyd.service
        mode: 0644

    - name: Activate TTYD systemd service
      systemd:
        name: ttyd
        state: started
        enabled: true
