#
# WARP
# Devbox Ansible Role Tasks
# Setup ttyd Web Terminal & Certbot for TLS
#

- name: Activate systemd service to start TTYD on boot
  block:
    - name: Write systemd service
      copy:
        content: |
          [Unit]
          Description=TTYD enables shell access a web terminal

          [Install]
          WantedBy=multi-user.target

          [Service]
          Type=simple
          ExecStart={{ devbox_ttyd_path }} --port 7681 /usr/bin/zsh
          User=mrzzy
          Group=mrzzy
          WorkingDirectory=/home/mrzzy
        dest: /etc/systemd/system/ttyd.service
        mode: 0644

    - name: Activate systemd service
      systemd:
        name: ttyd
        state: started
        enabled: true
