#
# WARP
# Devbox Ansible Role Tasks
# Setup User Accounts & Permissions
#

- name: Create groups
  become: true
  group:
    name: "{{ item }}"
    state: present
  loop:
    - sudo
    - docker
    - ssl-cert

- name: Create devbox user
  become: true
  user:
    name: "{{ devbox_user }}"
    home: "{{ devbox_user_home }}"
    shell: /bin/zsh
    groups:
      # sudo group for passwordless sudo
      - sudo
      # docker group for sudo-free access to the docker CLI
      - docker
      # access to TLS certificates
      - ssl-cert

- name: Allow password-less sudo to users in sudo group
  become: true
  copy:
    content: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/sudo_nopasswd
    mode: 0440

- name: Allow ssl-cert group members to access TLS private keys
  become: true
  file:
    path: /etc/ssl/private/
    group: ssl-cert
    mode: 0710
