#
# WARP
# Devbox Ansible Role
# Write iptables rules
#

- name: Write IPV4 iptables rules to be loaded on boot
  become: true
  vars:
    interface: "{{ ansible_default_ipv4.interface }}"
  copy:
    content: |
      *nat
      # forward incoming traffic via the default ipv4 interface to TTYD
      -A PREROUTING -i {{ interface }} -p tcp -m tcp --dport 80 -j REDIRECT --to-ports {{ devbox_ttyd_http_port }}
      -A PREROUTING -i {{ interface }} -p tcp -m tcp --dport 443 -j REDIRECT --to-ports {{ devbox_ttyd_https_port }}
      COMMIT
    dest: /etc/iptables/rules.v4
    mode: 0644
