#
# WARP
# Python Ansible Role
# Tasks
#

- name: Install Python & Tooling with APT
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    # python & tools
    - "python3={{ devbox_python_version }}"
    - "python3-venv={{ devbox_python_version }}"
    - "python3-pip={{ devbox_python_pip_version }}"
    - "python-wheel-common={{ devbox_python_wheel_version }}"

- name: Install Neovim client for Python with Pip
  become: true
  pip:
    name: "pynvim=={{ devbox_python_pynvim_version }}"
    state: present
