#
# WARP
# Python Ansible Role
# Tasks
#

- name: Install Python & Tooling with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    # python & tools
    - "python3.10={{ devbox_python_version }}"
    - "python3.10-venv={{ devbox_python_version }}"
    - "python3-pip={{ devbox_python_pip_version }}"
    - "python3-wheel={{ devbox_python_wheel_version }}"

- name: Install Python Tooling with Pip
  become: true
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - "jupyterlab=={{ devbox_python_jupyterlab_version }}"
    - "pynvim=={{ devbox_python_pynvim_version }}"
