#
# WARP
# Javascript Role
# Tasks
#

- name: Install JavaScript tools with NPM
  become: true
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    global: true
    state: present
  loop:
    - name: typescript
      version: "{{ devbox_typescript_version }}"
