#
# WARP
# Power management
# Tasks
#

- name: Install TLP with APT
  become: true
  ansible.builtin.apt:
    name: "tlp={{ devbox_tlp_version }}"
    state: present

- name: Install TLP config
  become: true
  ansible.builtin.copy:
    src: tlp-thinkpad-amd.conf
    dest: /etc/tlp.d/99-thinkpad-amd.conf
    mode: "0744"
