#
# WARP
# Power management
# Tasks
#

- name: Install TLP with APT
  become: true
  ansible.builtin.apt:
    name: "tlp={{ devbox_tlp_version }}"
    state: present

- name: Install Systemd sleep config
  become: true
  ansible.builtin.copy:
    content: |
      #
      # WARP
      # Systemd Sleep
      #

      [Sleep]
      AllowHibernation=yes
      AllowSuspendThenHibernate=yes
      # Hibernate after sleeping for 15 minutes.
      # Avoid high sleep time power drain due to S0 modern standby.
      HibernateDelaySec=15min
    dest: /etc/systemd/sleep.conf.d/99-suspend-then-hibernate.conf
    mode: "0744"
