#
# WARP
# CI Pipeline
#

name: CI Pipeline
on: push
jobs:
  build-box-vagrant:
    # macos runner is used as it supports nested virtualization,
    # needed by virtualbox vm to run within github actions runner.
    # it also comes with vagrant & virtualbox preinstalled
    # https://github.com/jonashackt/vagrant-github-actions
    runs-on: macos-10.15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python Tooling
      run: sudo pip3 install -r requirements.txt

    - name: Install Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.0

    - name: Build Dev Box using Packer + Vagrant
      run: make box

  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Install Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.7.10
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.17"

    - name: Install Python Tooling
      run: |
        set -ex -o pipefail
        sudo pip3 install -r requirements.txt
        pre-commit install-hooks

    - name: Flag Secrets
      uses: zricethezav/gitleaks-action@v1.6.0

    - name: Lint code
      run: make lint
