#
# WARP
# CI Pipeline
# 

name: CI Pipeline
on: push
jobs:
  build-box-vagrant:
    # only macos runner supports nested virtualization, with vagrant & virtualbox preinstalled
    # needed by virtualbox vm to run within github actions runner
    # https://github.com/jonashackt/vagrant-github-actions
    runs-on: macos-10.15
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Install Python Tooling
      runs: pip3 install --user -r requirements.txt

    - name: Install Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.7.10

    - name: Build Dev Box using Packer + Vagrant
      run: make box
