#
# WARP
# Sync Terraform Module on Nimbus
#

name: Sync Revision of WARP Terraform Module on Nimbus
on:
  push:
    branches: [main]
    paths:
    - "deploy/terraform/**"
jobs:
  create-nimbus-pr:
    name: Create Pull Request to update WARP Terraform Module on Nimbus
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Nimbus repository
        uses: actions/checkout@v4
        with:
          repository: mrzzy/nimbus
      - name: Update revision of WARP Terraform Modules
        run: |
          sed -i -e \
            '/source.*=.*github.com\/mrzzy\/warp/s/ref=[^"]*/ref=${{ github.sha }}/' \
            terraform/gcp.tf
      - name: Create Pull Request on Nimbus
        uses: peter-evans/create-pull-request@v5
        with:
          token: "${{ secrets.GH_PUSH_TOKEN }}"
          # Commit
          commit-message: "build(terraform): bump revision of warp vm TF module"
          # Pull request
          branch: build/update-warp-tf-module
          title: "build(terraform): Update WARP VM Terraform module."
          body: "Update revision of WARP VM Terraform module to \
                 ${{ github.repository}}@${{ github.sha }}"
          delete-branch: true

      - name: Automerge Pull Request on Nimbus
        env:
          GH_TOKEN: "${{ secrets.GH_PUSH_TOKEN }}"
        run: gh pr merge --squash --auto ${PULL_REQUEST_NUMBER}
