#
# WARP
# GCP Ansible Role
# Tasks
#

- name: Setup GCP APT package repository
  vars:
    key_path: /etc/apt/keyrings/cloud.google.gpg
  become: true
  block:
    - name: Add GCP APT Package Signing Key
      ansible.builtin.copy:
        src: gcp_apt_key.gpg
        dest: "{{ key_path }}"
        mode: "0644"
    - name: Add GCP APT Package Repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_path }}] \
               https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present

- name: Install GCP tools with APT
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - google-cloud-sdk-gke-gcloud-auth-plugin
    - google-cloud-cli
